source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'
use_frameworks!

target 'podcastPlayer' do
 
  pod 'FeedKit', '9.1.2'
  pod 'Kingfisher' , '7.12.0'
  pod 'KingfisherWebP', '1.6.0'

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
  end
 end
end
